[build]
  command = "hugo"
  context = "production"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.107.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.107.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.107.0"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

